- include: upload.yaml

- hosts: 'nodes[0]'
  vars:
    root_dir: "{{playbook_dir}}/../.."
  tasks:
    - name: Upload gravity application
      become: yes
      shell:
        chdir: /installer/gravity
        cmd: ./upload

    - name: Start gravity upgrade
      become: yes
      shell:
        chdir: /installer/gravity
        cmd: ./gravity --insecure -q upgrade
      register: operation_id

    - name: Watch upgrade operation status
      become: yes
      action: shell gravity status --operation-id={{operation_id.stdout}} --quiet
      register: result
      until: result.stdout.find("completed") != -1
      retries: 50
      delay: 10

