---

- hosts: all
  become: yes
  tasks:
    - name: Enable epel-release
      yum:
        name: epel-release

    - name: Install required packages
      package:
        name:
          - curl
          - htop
          - iotop
          - lsof
          - ltrace
          - mc
          - net-tools
          - strace
          - tcpdump
          - telnet
          - vim
          - wget
          - chrony
          - traceroute
          - cloud-utils-growpart

    - name: Set up default opscenter hostname
      lineinfile:
        dest: /etc/hosts
        line: "{{ansible_default_ipv4.gateway}} opscenter.localhost.localdomain"

    - name: Load bridge netfilter module
      modprobe:
        name: br_netfilter

    - name: Load bridge netfilter module on start
      copy:
        dest: /etc/modules-load.d/br_netfilter.conf
        content: "br_netfilter"

    - name: Set bridge netfilter kernel parameters on start
      sysctl:
        sysctl_file: /etc/sysctl.d/10-br-netfilter.conf
        value: 1
        reload: yes
        name: "{{ item }}"
      with_items:
        - net.bridge.bridge-nf-call-arptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables

    - name: Grow partition until maximum
      command: growpart /dev/sda 1
      register: growpart
      ignore_errors: true

    - name: Extend the FS
      when: growpart.rc == 0
      filesystem:
        fstype: 'xfs'
        dev: '/dev/sda1'
        resizefs: yes
